CANDIDATE_SITES_DATA = [
    {
        "id": "SITE_NAG_01",
        "name": "Besa-Pipla Southern Growth Sector",
        "zone": "South Zone (Wardha Rd Fringe)",
        "latitude": 21.0782,
        "longitude": 79.0945,
        "area_sqm": 32400.0,
        "parcel_size_acres": 8.01,
        "land_use": "Public-Semi-Public Institutional",
        "slope_percent": 1.2,
        "elevation_m": 312.0,
        "est_acquisition_cost_inr_cr": 24.5,
        "population_2km": 42000,
        "population_5km": 188000,
        "population_10km": 540000,
        "estimated_underserved_pop": 125000,
        "distance_to_major_road_km": 0.35,
        "travel_time_min": 14.0,
        "road_type": "Outer Ring Road Arterial (4-lane)",
        "distance_to_nearest_hospital_km": 6.8,
        "hospitals_within_5km": 1,
        "nearest_hospital_name": "AIIMS Nagpur (Tertiary)",
        "distance_to_water_body_km": 1.85,
        "distance_to_protected_zone_km": 4.5,
        "is_in_flood_zone": False
    },
    {
        "id": "SITE_NAG_02",
        "name": "Wadi-Hingna Industrial Extension",
        "zone": "West Zone (Amravati Rd Corridor)",
        "latitude": 21.1415,
        "longitude": 78.9850,
        "area_sqm": 41200.0,
        "parcel_size_acres": 10.18,
        "land_use": "Mixed Commercial/Institutional",
        "slope_percent": 2.1,
        "elevation_m": 328.0,
        "est_acquisition_cost_inr_cr": 28.0,
        "population_2km": 56000,
        "population_5km": 210000,
        "population_10km": 620000,
        "estimated_underserved_pop": 164000,
        "distance_to_major_road_km": 0.15,
        "travel_time_min": 11.5,
        "road_type": "National Highway 53 Connector",
        "distance_to_nearest_hospital_km": 7.4,
        "hospitals_within_5km": 1,
        "nearest_hospital_name": "Lata Mangeshkar Hospital",
        "distance_to_water_body_km": 1.4,
        "distance_to_protected_zone_km": 3.8,
        "is_in_flood_zone": False
    },
    {
        "id": "SITE_NAG_03",
        "name": "Kamptee-Uppalwadi Logistics Belt",
        "zone": "North-East Corridor",
        "latitude": 21.2150,
        "longitude": 79.1620,
        "area_sqm": 28500.0,
        "parcel_size_acres": 7.04,
        "land_use": "Government Vacant Plot",
        "slope_percent": 1.8,
        "elevation_m": 305.0,
        "est_acquisition_cost_inr_cr": 16.8,
        "population_2km": 38000,
        "population_5km": 154000,
        "population_10km": 490000,
        "estimated_underserved_pop": 118000,
        "distance_to_major_road_km": 0.60,
        "travel_time_min": 19.0,
        "road_type": "State Highway 248",
        "distance_to_nearest_hospital_km": 8.2,
        "hospitals_within_5km": 0,
        "nearest_hospital_name": "Sub-District Hospital Kamptee",
        "distance_to_water_body_km": 0.95,
        "distance_to_protected_zone_km": 5.2,
        "is_in_flood_zone": False
    },
    {
        "id": "SITE_NAG_04",
        "name": "MIHAN Multi-Modal SEZ Edge",
        "zone": "South Special Economic Zone",
        "latitude": 21.0350,
        "longitude": 79.0520,
        "area_sqm": 56000.0,
        "parcel_size_acres": 13.84,
        "land_use": "Special Health/Institutional Reserve",
        "slope_percent": 0.9,
        "elevation_m": 315.0,
        "est_acquisition_cost_inr_cr": 38.0,
        "population_2km": 19000,
        "population_5km": 82000,
        "population_10km": 310000,
        "estimated_underserved_pop": 64000,
        "distance_to_major_road_km": 0.20,
        "travel_time_min": 16.0,
        "road_type": "Expressway Corridor (6-lane)",
        "distance_to_nearest_hospital_km": 3.2,
        "hospitals_within_5km": 2,
        "nearest_hospital_name": "AIIMS Nagpur",
        "distance_to_water_body_km": 2.6,
        "distance_to_protected_zone_km": 6.0,
        "is_in_flood_zone": False
    },
    {
        "id": "SITE_NAG_05",
        "name": "Gorewada Catchment Buffer Plot",
        "zone": "North-West Ecological Fringe",
        "latitude": 21.1980,
        "longitude": 79.0340,
        "area_sqm": 18000.0,
        "parcel_size_acres": 4.45,
        "land_use": "Agricultural/Restricted Green",
        "slope_percent": 4.8,
        "elevation_m": 342.0,
        "est_acquisition_cost_inr_cr": 12.0,
        "population_2km": 22000,
        "population_5km": 94000,
        "population_10km": 380000,
        "estimated_underserved_pop": 58000,
        "distance_to_major_road_km": 1.45,
        "travel_time_min": 24.5,
        "road_type": "Secondary Rural Road (2-lane)",
        "distance_to_nearest_hospital_km": 5.1,
        "hospitals_within_5km": 1,
        "nearest_hospital_name": "Alexis Multispecialty Hospital",
        "distance_to_water_body_km": 0.08,
        "distance_to_protected_zone_km": 0.25,
        "is_in_flood_zone": True
    },
    {
        "id": "SITE_NAG_06",
        "name": "Umred Road Dighori Expansion",
        "zone": "South-East Sector",
        "latitude": 21.1020,
        "longitude": 79.1480,
        "area_sqm": 35000.0,
        "parcel_size_acres": 8.65,
        "land_use": "Public Semi-Public",
        "slope_percent": 1.5,
        "elevation_m": 308.0,
        "est_acquisition_cost_inr_cr": 22.0,
        "population_2km": 49000,
        "population_5km": 195000,
        "population_10km": 580000,
        "estimated_underserved_pop": 142000,
        "distance_to_major_road_km": 0.30,
        "travel_time_min": 13.0,
        "road_type": "State Highway 9 Arterial",
        "distance_to_nearest_hospital_km": 7.1,
        "hospitals_within_5km": 0,
        "nearest_hospital_name": "Government Medical College (GMC)",
        "distance_to_water_body_km": 1.6,
        "distance_to_protected_zone_km": 4.1,
        "is_in_flood_zone": False
    },
    {
        "id": "SITE_NAG_07",
        "name": "Manewada Sub-Urban Parcel",
        "zone": "South-Central Cluster",
        "latitude": 21.1080,
        "longitude": 79.0980,
        "area_sqm": 9500.0,
        "parcel_size_acres": 2.35,
        "land_use": "Dense Residential Infill",
        "slope_percent": 0.8,
        "elevation_m": 310.0,
        "est_acquisition_cost_inr_cr": 19.5,
        "population_2km": 68000,
        "population_5km": 240000,
        "population_10km": 710000,
        "estimated_underserved_pop": 178000,
        "distance_to_major_road_km": 0.10,
        "travel_time_min": 9.0,
        "road_type": "Inner City Major Collector",
        "distance_to_nearest_hospital_km": 3.8,
        "hospitals_within_5km": 3,
        "nearest_hospital_name": "Orange City Hospital",
        "distance_to_water_body_km": 2.1,
        "distance_to_protected_zone_km": 5.5,
        "is_in_flood_zone": False
    }
]

EXISTING_HOSPITALS_DATA = [
    {"id": "HOSP_01", "name": "AIIMS Nagpur (Apex Tertiary)", "type": "Apex Tertiary Referral", "beds": 960, "emergency": True, "latitude": 21.0420, "longitude": 79.0480},
    {"id": "HOSP_02", "name": "Government Medical College (GMC)", "type": "Public Tertiary", "beds": 1400, "emergency": True, "latitude": 21.1340, "longitude": 79.0980},
    {"id": "HOSP_03", "name": "Alexis Multispecialty Hospital", "type": "Private Tertiary", "beds": 250, "emergency": True, "latitude": 21.1850, "longitude": 79.0750},
    {"id": "HOSP_04", "name": "Orange City Hospital & Research", "type": "Multispecialty Secondary", "beds": 220, "emergency": True, "latitude": 21.1180, "longitude": 79.0620},
    {"id": "HOSP_05", "name": "Lata Mangeshkar Hospital", "type": "Medical College Hospital", "beds": 750, "emergency": True, "latitude": 21.1120, "longitude": 78.9980}
]

ENVIRONMENTAL_CONSTRAINTS_DATA = [
    {"id": "ENV_01", "name": "Gorewada Bio-Park Reserve", "category": "Protected Forest", "latitude": 21.2020, "longitude": 79.0280, "radius_meters": 1200.0, "is_hard_exclusion": True, "description": "500m eco-sensitive buffer."},
    {"id": "ENV_02", "name": "Ambazari Lake Catchment", "category": "Urban Water Body", "latitude": 21.1290, "longitude": 79.0430, "radius_meters": 750.0, "is_hard_exclusion": True, "description": "Construction prohibited within 150m."}
]

POPULATION_ZONES_DATA = [
    {"id": "POP_01", "name": "Besa-Ghoghli Urban Ward", "total_population": 84000, "density_per_sqkm": 6800.0, "underserved_ratio": 0.65, "latitude": 21.0820, "longitude": 79.0920},
    {"id": "POP_02", "name": "Wadi Municipal Council", "total_population": 98000, "density_per_sqkm": 7200.0, "underserved_ratio": 0.72, "latitude": 21.1440, "longitude": 78.9910}
]

ROAD_NETWORKS_DATA = [
    {"id": "ROAD_01", "name": "Outer Ring Road Bypass", "type": "National Highway", "lanes": 6, "coordinates": [[21.0300, 79.0400], [21.0750, 79.0900], [21.1000, 79.1500]]}
]
